model_name: microsoft/codebert-base
train_file: data/processed/train_csharp_bugs_enhanced.jsonl   
valid_file: data/processed/valid_csharp_bugs_enhanced.jsonl
output_dir: data/models/codebert_bug
num_epochs: 4
batch_size: 8
max_seq_len: 512
lr: 2e-5
weight_decay: 0.01
warmup_ratio: 0.06
seed: 42
  